# Generated by Django 5.2.3 on 2025-11-21 02:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('advertisements', '0002_comment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
