# Generated by Django 5.2.3 on 2025-11-03 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='name',
            field=models.CharField(max_length=32, verbose_name='Имя'),
        ),
    ]
